import type { Metadata } from "next";
import "./globals.css";
import { Setup } from "./setup";

// 创建一个新的 QueryClient 实例
// const queryClient = new QueryClient()

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Setup>{children}</Setup>
      </body>
    </html>
  );
}
